# yaml文件可以用yaml后缀 也可以yml。文件内部不大写
person:
  name: 张三
  #字符串可以不用引号，可以用单引号和双引号
  #单引号内的\n会作为字符串内部的字符输出 即不引起转义
  #双引号内的\n会作为换行换行输出 引起转义
  boss: false
  birthday: 1986/12/9
  age: 35
  #数组的表示方法
  #interests: [basketball,football,tennis]
  interests:
    - basketball
    - football
    - tennis
  #list,set和数组一样
  animal: [cat,dog,snake]
  #map kv的表示方式
  #score: {english: 80,math: 60}
  score:
    english: 80
    math: 60
  #set的表示方法
  salarys:
    - 99
    - 98
  #单个对象的表示方法
  pet:
    #对象内部属性
    name: doggie
    weight: 10
  #对象集合的表示方法
  allPets:
    #key
    sick:
      #2种表示方法,添加三个key为sick 在list里的pet对象
      - {name: doggie,weight: 12}
      - name: cat
        weight: 20
      - name: butterfly
        weight: 1
    health:
      - {name: fish,weight: 2}

